global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:6379']

  # Add more targets like your FastAPI app if needed
